root: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
env:
  es2018: true
  node: true
extends: eslint:recommended
ignorePatterns:
  - 'node_modules/*'
rules: {}
settings:
  import/ignore:
    - 'src/worker/worker/textlint-worker\\.js$'
overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    plugins:
      - prefer-arrow
    extends:
      - plugin:import/errors
      - plugin:import/warnings
      - plugin:import/typescript
      - plugin:react/recommended
      - plugin:jsx-a11y/recommended
      - plugin:@typescript-eslint/recommended
      - plugin:prettier/recommended
    rules:
      '@typescript-eslint/explicit-function-return-type':
        - 'off'
      '@typescript-eslint/explicit-module-boundary-types':
        - 'off'
      '@typescript-eslint/no-empty-function':
        - 'off'
      '@typescript-eslint/no-explicit-any':
        - 'off'
      '@typescript-eslint/no-unused-vars':
        - warn
        - args: after-used
          argsIgnorePattern: _
          ignoreRestSiblings: false
          vars: all
          varsIgnorePattern: _
      '@typescript-eslint/no-use-before-define':
        - error
      '@typescript-eslint/prefer-nullish-coalescing': error
      '@typescript-eslint/prefer-optional-chain': error
      import/default: off
      import/extensions:
        - error
        - ignorePackages
        - ts: never
          tsx: never
      import/first: error
      import/newline-after-import: error
      import/no-duplicates: error
      import/no-named-as-default: off
      import/no-named-as-default-member: off
      import/no-unresolved: off
      import/order:
        - error
        - alphabetize:
            caseInsensitive: true
            order: asc
          groups:
            - builtin
            - external
            - internal
            - parent
            - sibling
            - index
            - object
          newlines-between: always
      import/prefer-default-export: off
      linebreak-style:
        - error
        - unix
      lines-between-class-members:
        - error
        - always
        - exceptAfterSingleLine: true
      no-unused-vars: off
      no-use-before-define: off
      no-void:
        - error
        - allowAsStatement: true
      padding-line-between-statements:
        - error
        - blankLine: always
          next: return
          prev: '*'
      prefer-arrow/prefer-arrow-functions:
        - error
        - classPropertiesAllowed: false
          disallowPrototype: true
          singleReturnOnly: false
      prettier/prettier:
        - error
        - {}
        - usePrettierrc: true
      react/function-component-definition:
        - 2
        - namedComponents: arrow-function
      react/jsx-filename-extension:
        - 1
        - extensions:
            - .tsx
      react/prop-types: off
      react/react-in-jsx-scope: off
    settings:
      import/resolver:
        typescript: {}
      react:
        version: detect
